"""
Kyrgyz TTS via AkylAI Matcha-TTS.

The official Hugging Face model card for kyrgyz-ai/akylai-tts-mini documents
CLI inference through `matcha-tts --text ...`. The model is not available
through Hugging Face Inference Providers, so production runs it locally inside
the TTS container.
"""
from __future__ import annotations

import asyncio
import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

AKYLAI_MIME_TYPE = "audio/wav"
_MATCHA_CMD = os.getenv("AKYLAI_MATCHA_CMD", "matcha-tts")
_SPEAKING_RATE = os.getenv("AKYLAI_SPEAKING_RATE", "1.0")
_TEMPERATURE = os.getenv("AKYLAI_TEMPERATURE", "0.667")
_STEPS = os.getenv("AKYLAI_STEPS", "10")
_TIMEOUT_SECONDS = int(os.getenv("AKYLAI_TIMEOUT_SECONDS", "90"))


async def synthesize(text: str, voice_type: str = "female") -> bytes:
    """Return WAV bytes of Kyrgyz speech generated by AkylAI/Matcha-TTS."""
    del voice_type
    return await asyncio.to_thread(_synthesize_sync, text)


async def synthesize_with_timing(
    text: str, voice_type: str = "female"
) -> tuple[bytes, list[dict]]:
    """Return WAV bytes plus approximate word timings for 3D lip-sync."""
    audio = await synthesize(text, voice_type)
    return audio, _estimate_word_boundaries(text)


def _synthesize_sync(text: str) -> bytes:
    if shutil.which(_MATCHA_CMD) is None:
        raise RuntimeError(
            "AkylAI Kyrgyz TTS is not installed: `matcha-tts` was not found. "
            "Install Akyl-AI/tts-mini in the TTS service image."
        )

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        command = [
            _MATCHA_CMD,
            "--text",
            text,
            "--speaking_rate",
            _SPEAKING_RATE,
            "--temperature",
            _TEMPERATURE,
            "--steps",
            _STEPS,
        ]
        logger.info("AkylAI Kyrgyz TTS: len=%d cmd=%s", len(text), _MATCHA_CMD)

        try:
            result = subprocess.run(
                command,
                cwd=tmp,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=_TIMEOUT_SECONDS,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError(
                f"AkylAI Kyrgyz TTS timed out after {_TIMEOUT_SECONDS}s."
            ) from exc

        audio_files = sorted(
            [*tmp.rglob("*.wav"), *tmp.rglob("*.mp3")],
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
        if result.returncode != 0 or not audio_files:
            detail = "\n".join(
                part for part in [result.stdout, result.stderr] if part
            ).strip()
            raise RuntimeError(
                "AkylAI Kyrgyz TTS failed"
                + (f": {detail[-2000:]}" if detail else ".")
            )

        return audio_files[0].read_bytes()


def _estimate_word_boundaries(text: str) -> list[dict]:
    words = [word for word in text.split() if word.strip()]
    if not words:
        return []

    # AkylAI CLI does not expose word boundaries. Approximate timings keep the
    # 3D avatar's mouth moving instead of leaving lip-sync disabled for Kyrgyz.
    ms_per_word = 420
    return [
        {
            "word": word.strip(".,!?;:"),
            "offset_ms": idx * ms_per_word,
            "duration_ms": min(360, max(180, len(word) * 45)),
        }
        for idx, word in enumerate(words)
    ]
